### ISSUE TITLE
Event in the future

### ISSUE THREAD

**Issue by jonasmora** [Unity-Technologies/InputSystem#231]
https://github.com/Unity-Technologies/InputSystem/blob/184e4531cf0f39c63cfb92f47e6cebb8791aa145/Packages/com.unity.inputsystem/InputSystem/InputManager.cs#L1911

I'm getting an event in the future, or at least that's what I think.

I'm printing the following under L1911:

```cs
Debug.Log("[InputManager.OnUpdate] currentEventType: " + currentEventType + ", InputRuntime.s_Instance.currentTime: " + InputRuntime.s_Instance.currentTime + ", currentEventTimeInternal: " + currentEventTimeInternal + ", (InputRuntime.s_Instance.currentTime - currentEventTimeInternal): " + (InputRuntime.s_Instance.currentTime - currentEventTimeInternal));
```

And I'm getting this:

> [InputManager.OnUpdate] currentEventType: STAT, InputRuntime.s_Instance.currentTime: 74.9484100341797, currentEventTimeInternal: 76.9885741380202, (InputRuntime.s_Instance.currentTime - currentEventTimeInternal): -2.04015647444595

I'm running on Android using Unity 2018.2.4f1

Please advice.

**Comment by Rene-Damm** [comment]
There's some changes in Unity 2018.2.5 that are needed by the recent event time changes in C#. As of the latest head on the develop branch, the code shouldn't build with previous versions of Unity anymore. Upgrading to 2018.2.5 should fix the problem here.

**Comment by jonasmora** [comment]
I'm sorry to inform you but I'm still having the same issue using 2018.2.5f1, is that possible?

**Comment by jonasmora** [comment]
I'm going to pull the latest code from develop branch.

**Comment by jonasmora** [comment]
I'm getting this error with the latest develop code:

> Assets/Packages/com.unity.inputsystem/InputSystem/InputSystem.cs(1541,51): error CS0426: The nested type `SerializedState' does not exist in the type `UnityEngine.Experimental.Input.InputRemoting'

**Comment by jonasmora** [comment]
I removed the compiler flag UNITY_EDITOR from InputSystem/Packages/com.unity.inputsystem/InputSystem/Devices/Remote/InputRemoting.cs and was able to make a build.

I can confirm that this issue is solved, the new output is this:

> [InputManager.OnUpdate] currentEventType: STAT, InputRuntime.s_Instance.currentTime: 39.6235421720194, currentEventTimeInternal: 39.6012166510229, (InputRuntime.s_Instance.currentTime - currentEventTimeInternal): 0.0223286979706003

**Comment by Rene-Damm** [comment]
Crap, sorry about the InputRemoting build problem. Will push a fix. We're in the process of setting up proper build and test automation so stuff like this doesn't happy anymore.

Happy to hear that otherwise the issue is resolved. Thanks for confirming.
