### ISSUE TITLE
Keyboard keys not reporting accurately

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#25]
Pressing this key on keyboard > causes InputSystem to report this key

Numpad + > Numpad -
Numpad - > Numpad *
Numpad * > Numpad /
Numpad / > Numpad =

I don't yet have a keyboard with a numpad equals sign.  Will update when I find one.

**Comment by jackpr-unity** [comment]
Found a keyboard with a numberpad = sign.  In one test it registered as a '5' - on the next test when I tried to differentiate between numperpad 5 and digit 5, it did not report as anything.

Backslash reports accurately through Keyboard.onTextInput, but updates Keyboard.OEM1.value instead of Keyboard.Backslash.value

**Comment by jackpr-unity** [comment]
Keyboard.Digit9.value does not update.  Keyboard.onTextInput does work for this key.

**Comment by jackpr-unity** [comment]
Pressing Insert, Home, PageUp, Delete, End, PageDown report correctly from Keyboard.current[], but also seem to change the state of the print screen button.

Odd, rebooting fixed this specific issue.  Rebooting also fixed the numpad= reporting as 5, so there is some sort of odd state that the editor is slipping into.  Possibly related, possibly its own issue.

**Comment by jackpr-unity** [comment]
^ All of the above were tested in the Windows Editor

**Comment by Rene-Damm** [comment]
>Pressing Insert, Home, PageUp, Delete, End, PageDown report correctly from Keyboard.current[], but also seem to change the state of the print screen button.
>Odd, rebooting fixed this specific issue. Rebooting also fixed the numpad= reporting as 5, so there is some sort of odd state that the editor is slipping into. Possibly related, possibly its own issue.

Rebooting the machine or restarting Unity? Did you try the latter?

Does indeed sound like the keyboard code is getting into some weird state.

>Keyboard.Digit9.value does not update. Keyboard.onTextInput does work for this key.
>Backslash reports accurately through Keyboard.onTextInput, but updates Keyboard.OEM1.value instead of Keyboard.Backslash.value

These and numpad issues fixed in 16b4ab363780.

Temporarily removed support for numpad= on Windows.

**Comment by jackpr-unity** [comment]
> Pressing Insert, Home, PageUp, Delete, End, PageDown report correctly from Keyboard.current[], but also seem to change the state of the print screen button.
> Odd, rebooting fixed this specific issue. Rebooting also fixed the numpad= reporting as 5, so there is some sort of odd state that the editor is slipping into. Possibly related, possibly its own issue.

> 
> Rebooting the machine or restarting Unity? Did you try the latter?
> 
> Does indeed sound like the keyboard code is getting into some weird state.

I couldn't repro it, unfortunately.  I'm not sure how it got in that state.  It was relaunching the editor that fixed it.

**Comment by Rene-Damm** [comment]
Ok, something to keep an eye on. Definitely sounds like a bug either in the new backend or in the state keeping.

**Comment by Rene-Damm** [comment]
Everything except for numpad= should be fixed on trunk. Numpad= needs testing.

**Comment by JiaUnity** [comment]
Waiting for the Numpad= to be checked.

**Comment by jackpr-unity** [comment]
Testing with Unity 2018.3.5f1 and commit d8e3ad0553d91e81cb48d660becafb9af075f71b

Progress, but some issues remain.  I found these issues using the ISX_KB_Mouse_Basic scene
- alpha 9 sets keyboard state for alpha 8.  Alpha 8 still correctly sets keyboard state for alpha 8.  Keyboard.onTextInput correctly reports when the alpha 9 key is pressed.
- I ran into the print screen issue again.  Once again it won't repro. This time it was unplugging the usb and then plugging it back in that fixed the issue. Possibly a mac keyboard thing?  I've never seen this happen on my Microsoft keyboard or laptop keyboard.
- The numpad = key doesn't report at all
- Numpad numbers don't report through Keyboard.onTextInput. Should they?

**Comment by michaeleconomy** [comment]
I had an issue where my Keyboard.current.leftShift.isPressed was returning the opposite state, but restarting unity fixed it.   using input system 0.2.0 - unity 2018.3.0f2

**Comment by jackpr-unity** [comment]
All issues I had seem fixed using 2019.1.0b8 and package commit 717086861b14d71bca05636c5d6af72491820040

@JiaUnity can you verify that all keys work correctly using the mac keyboard as well (especially numpad '=')?

**Comment by JiaUnity** [comment]
> @JiaUnity can you verify that all keys work correctly using the mac keyboard as well (especially numpad '=')?

The numpad = still doesn't work.

**Comment by JiaUnity** [comment]
Closing. For the issue is tracked: https://issuetracker.unity3d.com/issues/windows-keyboard-when-using-mac-magic-keyboard-equals-in-the-numpad-is-not-detected-at-all
