### ISSUE TITLE
Device debug view breaks if reading values throws exceptions

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#30]
Should have try/catch block(s) to protect against that.

**Comment by JiaUnity** [comment]
@Rene-Damm @todi1856 does it mean this one is fixed now?

**Comment by Rene-Damm** [comment]
I think the reference to #30 is erroneous. Not sure how that came to be. But the merge commit is unrelated to this issue. Pretty sure the issue is still in the code.

**Comment by JiaUnity** [comment]
Filed on FB. Closing.
