### ISSUE TITLE
XBox One and PS4 Controller Left Stick reporting bad values when used as DPad Composite

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#325]
I will create a better test case tomorrow, but When I set up a leftStick as a DPad composite using the leftStick/up...down...etc bindings, it seems to report bad values for left and down. This occurs when Normalize is checked and unchecked.

Tested on 2018.3b12, Windows 10. Commit: a27f9957d7b4a2e9668cdf43c2cbd085b217d022

**Comment by Rene-Damm** [comment]
Hmm, not sure what's up there. The following test passes for me.

```
    [Test]
    [Category("Actions")]
    public void Actions_CanCreateDpadComposite_FromStickDirections()
    {
        var gamepad = InputSystem.AddDevice<Gamepad>();

        var action = new InputAction();
        action.AddCompositeBinding("Dpad")
            .With("Up", "<Gamepad>/leftStick/up")
            .With("Down", "<Gamepad>/leftStick/down")
            .With("Left", "<Gamepad>/leftStick/left")
            .With("Right", "<Gamepad>/leftStick/right");
        action.Enable();

        Vector2? value = null;
        action.performed += ctx => value = ctx.ReadValue<Vector2>();
        
        // Up.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(0.0f, 0.5f));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value, Is.EqualTo(Vector2.up));

        // Up left.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(-0.34f, 5f));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value.x, Is.EqualTo((Vector2.up + Vector2.left).normalized.x).Within(0.00001));
        Assert.That(value.Value.y, Is.EqualTo((Vector2.up + Vector2.left).normalized.y).Within(0.00001));

        // Left.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(-0.45f, 0));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value, Is.EqualTo(Vector2.left));

        // Down left.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(-0.45f, -0.67f));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value.x, Is.EqualTo((Vector2.left + Vector2.down).normalized.x).Within(0.00001));
        Assert.That(value.Value.y, Is.EqualTo((Vector2.left + Vector2.down).normalized.y).Within(0.00001));

        // Down.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(0, -0.67f));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value, Is.EqualTo(Vector2.down));

        // Down right.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(0.56f, -0.67f));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value.x, Is.EqualTo((Vector2.down + Vector2.right).normalized.x).Within(0.00001));
        Assert.That(value.Value.y, Is.EqualTo((Vector2.down + Vector2.right).normalized.y).Within(0.00001));

        // Right.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(0.56f, 0));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value, Is.EqualTo(Vector2.right));

        // Up right.
        value = null;
        InputSystem.QueueDeltaStateEvent(gamepad.leftStick, new Vector2(0.56f, 0.23f));
        InputSystem.Update();

        Assert.That(value, Is.Not.Null);
        Assert.That(value.Value.x, Is.EqualTo((Vector2.right + Vector2.up).normalized.x).Within(0.00001));
        Assert.That(value.Value.y, Is.EqualTo((Vector2.right + Vector2.up).normalized.y).Within(0.00001));
    }
```

What's the bad values you are getting? Wondering if the problem is actually in the Xbox gamepad layout rather than the action side stuff.

**Comment by periodyctom** [comment]
That's very likely.

What I'm getting is either no down or left, or bad values for down or left (basically left just gives me right, as in: left (1, 0) right (1, 0).

I'm at work atm, but I'll try and get you my action map file when I can. Switching back to a normal stick control gives me correct analog values, so it's something with the layout or binding handling.

**Comment by periodyctom** [comment]
EDIT: Confirmed happening on e8ac9f1895be5739a74f11a8cba3ed8cb8ea5e4b, I haven't tested preview 13 yet.
Tested on two different windows machines, wired and wireless XBOX One controller, same results. The left and down directions from the gamepad left stick are producing bad values or zero.

Copy: of my input assets file and generated script. Note that I disabled normalization, Interactions, and processors across all 3 Dpad composites to make sure the values are coming through without modification that could change the results:
[TiTestInputs.zip](https://github.com/Unity-Technologies/InputSystem/files/2648154/TiTestInputs.zip)

Log where I used the stick directions with composite DPad. I started the stick direction in down/left (SouthWestern) direction and rotated counter-clockwise a few times.
[StickDpadLog.log](https://github.com/Unity-Technologies/InputSystem/files/2648156/StickDpadLog.log)

Log where I used the gamepad dpad:
[GamepadDPad.log](https://github.com/Unity-Technologies/InputSystem/files/2648179/GamepadDPad.log)

Keyboard Arrows:
[KeyboardArrowKeys.log](https://github.com/Unity-Technologies/InputSystem/files/2648186/KeyboardArrowKeys.log)

In this script, I read from the traces associated with each player's action map, and process the inputs to ECS data. Axis directions are converted to [numpad notation](http://www.dustloop.com/wiki/index.php/Notation):

[TitaniumInputUserHandler.zip](https://github.com/Unity-Technologies/InputSystem/files/2648192/TitaniumInputUserHandler.zip)

I can provide more of the current project files upon request.

**Comment by Rene-Damm** [comment]
>What I'm getting is either no down or left, or bad values for down or left (basically left just gives me right, as in: left (1, 0) right (1, 0).

Wait, that part is actually expected. Sounds like the same thing that came up in #356.

`up`, `down`, `left`, and `right` are set up as buttons (i.e. [0..1]). Just like the ones on `dpad`.

Seems like it's a source of confusion, though, so could be that setup needs revisiting.

**Comment by douglas-piconi** [comment]
Should be fixed in 0.2.0-preview.

**Comment by periodyctom** [comment]
Still occurs in 0.20-preview. Occurs with both XBox One and PS4 controllers on PC. It looks like the zero reference point is incorrect, as neutral causes it to spit out values constantly. The directional values are different between the 2 controller types but the behavior is the same.

Unity Version is 2019.1b4, happens on b3 as well.

I confirmed the behavior by wiping my package cache and ensuring I had no github versions of the package.

Occurs with or without deadzoning processor, and with or without new Continous flag.

For instance, My XBox One pad spits out (0,1) in the neutral deadzone position, but (0,0) when I press it straight down.

The PS4 seems to only have values rotated at diagonals, it's a bit harder to tell what's going on.

In both cases the Root Action type is DPad, and I'm individuall mapping the stick directions with the general [gamepad] bindings, not platform specific.

Attached is my current Input actions file:
[TiTestInputsActions.zip](https://github.com/Unity-Technologies/InputSystem/files/2897529/TiTestInputsActions.zip)

**Comment by periodyctom** [comment]
After some testing and fiddling, I've been able to use the "Invert" processor trick that was mentioned on the Forums to get my XBox One controller to report values correctly. (I did have to use an custom axis deadzone to get actual 0 values however).

I'll test against the PS4 controller again with my new inputactions setup and see if it's not just a config issue. If so I'll close this out.

**Comment by periodyctom** [comment]
Tested with an XBOX One and PS4 controller on 2 different windows boxes. 

XBOX One controller now works as intended with the addition of Invert and AxisDeadzone processors.
PS4 controller still has issues with left to down range (around the 120 degree to 300 degree range) and I'm not sure if that's noise from the gyro or bad values from the stick.

Should I close this out and create/find a separate bug report?

**Comment by douglas-piconi** [comment]
If you wouldn't mind closing this,  and we can have a clean new bug on what exists right now.  Thank you for all the testing help on this.
